# Generated by Django 5.1.5 on 2025-01-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='url',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_price',
        ),
        migrations.AddField(
            model_name='details',
            name='delivery_time_in_days',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='details',
            name='offer_type',
            field=models.CharField(blank=True, default='basic', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='details',
            name='revisions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='title',
            field=models.CharField(default='Untitled Detail', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(default='No description provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default='Untitled Offer', max_length=255),
        ),
    ]
