# Generated by Django 5.1.5 on 2025-01-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0002_remove_details_url_remove_offer_min_delivery_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Detail', max_length=255)),
                ('revisions', models.IntegerField(default=0)),
                ('delivery_time_in_days', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('features', models.JSONField(default=list)),
                ('offer_type', models.CharField(blank=True, default='basic', max_length=50, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_details', to='coderr_app.offer')),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
